export type AssetCategory = 'commercial' | 'industrial';
export type AcquisitionPurpose = 'investment' | 'ownerOccupied' | 'relatedPartyLease' | 'vacant' | 'partiallyVacant' | 'mixedUse' | 'development';
export type LeaseStatus = 'fullyLeased' | 'partiallyLeased' | 'vacant' | 'monthToMonth' | 'relatedPartyLease' | 'leasePending';
export type StateTerritory = 'NSW' | 'VIC' | 'QLD' | 'WA' | 'SA' | 'TAS' | 'ACT' | 'NT';
export type PurchaserStructure = 'individual' | 'company' | 'discretionaryTrust' | 'unitTrust' | 'smsf' | 'holdingCompany' | 'spv' | 'operatingBusiness' | 'other';
export type TriState = 'yes' | 'no' | 'unknown';
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type RiskRating = 'green' | 'amber' | 'red' | 'specialistReview';
export type BindingConstraint = 'lvr' | 'icr' | 'dscr' | 'debtYield' | 'liquidity' | 'valuation' | 'fundsToComplete' | 'riskOverlay' | 'specialistReview' | 'none';
export type PurchaseAbilityStatus = 'supportable' | 'supportableSubjectToVerification' | 'equityShortfall' | 'notSupportable' | 'specialistReviewRequired';
export type NoiBasis = 'actual' | 'stabilised' | 'lenderAdjusted';
export type LenderPolicyProfileKey = 'conservativeBank' | 'mainstreamCommercialBank' | 'nonBankCommercial' | 'privateCreditShortTerm' | 'smsfCommercial' | 'ownerOccupiedBusinessLending' | 'custom';
export type GstTreatment = 'gstInclusive' | 'plusGst' | 'gstFreeGoingConcern' | 'marginScheme' | 'unknown';

export interface DealProfile { assetCategory: AssetCategory; assetSubtype: string; acquisitionPurpose: AcquisitionPurpose; leaseStatus: LeaseStatus; state: StateTerritory; proposedLoan?: number; }
export interface PurchaserProfile { purchaserType: PurchaserStructure; borrowerEntityName?: string; corporateTrustee?: 'yes' | 'no' | 'notApplicable'; guaranteesAvailable?: TriState; relatedPartyTenant?: boolean; gstRegistered?: TriState; availableCashEquity: number; sponsorLiquidity: number; liquidityMultiplier: number; existingBusinessDebts?: number; existingBusinessEbitda?: number; existingRentPaid?: number; proposedRentPayable?: number; trusteeDetails?: string; smsfBalance?: number; memberContributions?: number; lrbaRequired?: TriState; bareTrustRequired?: TriState; smsfRelatedPartyTenant?: TriState; smsfSpecialistReviewRequired?: boolean; }
export interface PropertyValuation { purchasePrice: number; estimatedMarketValue: number; bankValuation?: number; useConservativeValuation: boolean; landArea?: number; buildingArea?: number; lettableArea?: number; marketRentPerSqm?: number; passingRentPerSqm?: number; estimatedCapRate?: number; valuationConfidence: 'low' | 'medium' | 'high'; siteCoverageRatio?: number; clearanceHeight?: number; rollerDoors?: number; dockAccess?: boolean; onGradeLoading?: boolean; hardstandYardArea?: number; truckAccessQuality?: 'poor' | 'average' | 'good' | 'excellent'; powerCapacity?: 'unknown' | 'singlePhase' | 'threePhase' | 'highCapacity' | 'substationPresent'; slabCondition?: 'unknown' | 'good' | 'average' | 'poor'; roofCondition?: 'unknown' | 'good' | 'average' | 'poor'; }
export interface IncomeInputs { grossPassingRent: number; otherIncome: number; recoveredOutgoings: number; marketRent: number; vacancyAllowancePct: number; incentivesAdjustment: number; tenantArrearsAdjustment: number; nonRecoverableExpenses: number; councilRates: number; water: number; landTax: number; insurance: number; strataOwnersCorp: number; managementFees: number; repairsMaintenance: number; utilities: number; cleaning: number; security: number; otherExpenses: number; leaseCommencementDate?: string; leaseExpiryDate?: string; wale: number; optionsRemaining?: number; rentReviewType?: 'cpi' | 'fixedPct' | 'marketReview' | 'turnoverRent' | 'noneUnknown'; tenantCovenant: 'government' | 'nationalTenant' | 'listedCompany' | 'establishedSme' | 'newBusiness' | 'relatedParty' | 'weakUnknown'; rentOverMarket: TriState; percentageAboveMarket?: number; noiBasis: NoiBasis; }
export interface AcquisitionCosts { depositPaid: number; stampDuty: number; transferRegistrationFee: number; mortgageRegistrationFee: number; pexaSettlementFee: number; legalConveyancingFee: number; bankLegalFee: number; valuationFee: number; loanApplicationFee: number; buyersAgentFee: number; buildingInspection: number; pestInspection: number; structuralInspection: number; fireComplianceInspection: number; planningZoningReview: number; environmentalReport: number; asbestosReport: number; dueDiligence: number; capexReserve: number; workingCapitalReserve: number; otherAcquisitionCosts: number; gstTreatment: GstTreatment; gstAmount: number; gstClaimable: TriState; gstCashflowRequired: TriState; }
export interface LendingAssumptions { profile: LenderPolicyProfileKey; contractInterestRatePct: number; assessmentBufferPct: number; loanTermYears: number; interestOnlyPeriodYears: number; amortisationYears: number; maxLvr: number; minIcr: number; minDscr: number; minDebtYield: number; debtYieldEnabled: boolean; }
export interface RiskInputs { tenantStrength?: 'strong' | 'established' | 'weak' | 'unknown'; vacancyLevel?: 'none' | 'minor' | 'major'; rentComparedToMarket?: 'belowOrAtMarket' | 'moderatelyOver' | 'materiallyOver' | 'unknown'; incentivesSideAgreements?: TriState; outgoingsRecovery?: 'full' | 'partial' | 'unknown'; locationQuality?: 'good' | 'average' | 'poor'; buildingCondition?: 'good' | 'average' | 'poor'; zoningCertainty?: 'clear' | 'uncertain' | 'notPermitted'; arrears?: TriState; leaseDocumentationComplete?: TriState; fireCompliance?: TriState; environmentalRisk?: 'low' | 'unknown' | 'present' | 'knownContamination'; asbestosRisk?: 'low' | 'unknown' | 'likely' | 'confirmed'; tradeWasteRequirements?: TriState; dangerousGoodsUse?: TriState; specialisedImprovements?: TriState; tenantOperatorSpecialisation?: TriState; makeGoodObligations?: TriState; capexRequired?: 'none' | 'some' | 'heavy'; }
export interface BorrowingInputs { dealProfile: DealProfile; purchaserStructure: PurchaserProfile; propertyValuation: PropertyValuation; income: IncomeInputs; acquisitionCosts: AcquisitionCosts; lendingAssumptions: LendingAssumptions; riskInputs: RiskInputs; }
export interface NoiResult { potentialGrossIncome: number; vacancyLoss: number; effectiveGrossIncome: number; totalOperatingExpenses: number; actualNoi: number; stabilisedNoi: number; lenderAdjustedNoi: number; selectedNoi: number; adjustments: string[]; }
export interface RiskOverlayResult { level: RiskLevel; score: number; noiHaircutPct: number; lvrAdjustmentPct: number; icrAdjustment: number; dscrAdjustment: number; additionalCapexReserve: number; warnings: string[]; specialistReview: boolean; riskAdjustedAssetCap?: number; }
export interface FundsToCompleteResult { totalAcquisitionCosts: number; gstCashflowRequirement: number; totalCostBase: number; requiredEquity: number; equitySurplusShortfall: number; warnings: string[]; }
export interface BorrowingResult { propertyValueUsedForLvr: number; propertySupportedLoan: number; sponsorSupportedUplift: number; finalRiskAdjustedLoan: number; proposedLoan?: number; bindingConstraint: BindingConstraint; impliedLvr: number; assessmentRate: number; icr: number; dscr: number; debtYield: number; annualInterest: number; annualDebtService: number; componentCaps: { lvrCap: number; icrCap: number; dscrCap: number; debtYieldCap: number; liquidityCap: number | null; riskAdjustedCap: number | null; }; noi: NoiResult; fundsToComplete: FundsToCompleteResult; purchaseAbilityStatus: PurchaseAbilityStatus; riskRating: RiskRating; primaryReason: string; secondaryRisks: string[]; requiredNextAction: string; warnings: string[]; documentChecklist: string[]; commentary: string; scenarios: Array<{ name: string; maxLoan: number; requiredEquity: number; impliedLvr: number; icr: number; dscr: number; debtYield: number; riskRating: RiskRating; bindingConstraint: BindingConstraint; }>; }
