export type AssetCategory = 'commercial' | 'industrial';
export type AcquisitionPurpose = 'investment' | 'ownerOccupied' | 'relatedPartyLease' | 'vacant' | 'partiallyVacant' | 'mixedUse' | 'development';
export type LeaseStatus = 'fullyLeased' | 'partiallyLeased' | 'vacant' | 'monthToMonth' | 'relatedPartyLease' | 'leasePending';
export type StateTerritory = 'NSW' | 'VIC' | 'QLD' | 'WA' | 'SA' | 'TAS' | 'ACT' | 'NT';
export type PurchaserStructure = 'individual' | 'company' | 'discretionaryTrust' | 'unitTrust' | 'smsf' | 'holdingCompany' | 'spv' | 'operatingBusiness' | 'other';
export type TriState = 'yes' | 'no' | 'unknown';
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type RiskRating = 'green' | 'amber' | 'red' | 'specialistReview';
export type CreditAssessmentStatus = RiskRating;
export type BindingConstraint = 'lvr' | 'icr' | 'dscr' | 'debtYield' | 'liquidity' | 'valuation' | 'fundsToComplete' | 'riskOverlay' | 'specialistReview' | 'none';
export type PurchaseAbilityStatus = 'supportable' | 'supportableSubjectToVerification' | 'equityShortfall' | 'notSupportable' | 'specialistReviewRequired';
export type NoiBasis = 'actual' | 'stabilised' | 'lenderAdjusted';
export type LenderPolicyProfileKey = 'conservativeBank' | 'mainstreamCommercialBank' | 'nonBankCommercial' | 'privateCreditShortTerm' | 'smsfCommercial' | 'ownerOccupiedBusinessLending' | 'custom';
export type GstTreatment = 'gstInclusive' | 'plusGst' | 'gstFreeGoingConcern' | 'marginScheme' | 'unknown';
export type AssessmentBasis = 'contractPlusBuffer' | 'higherOfBufferAndFloor' | 'interestOnlyAssessment' | 'principalAndInterestAssessment' | 'custom';
export type RepaymentType = 'interestOnly' | 'principalAndInterest' | 'residualTerm';
export type ExitStrategy = 'refinance' | 'sale' | 'cashflowRepayment' | 'unknown';
export type CapexMode = 'manualOnly' | 'autoOnly' | 'manualPlusAuto';
export type WarningCategory = 'financial' | 'data' | 'asset' | 'structure' | 'lender' | 'gstDuty' | 'specialistReview';

export interface DealProfile { assetCategory: AssetCategory; assetSubtype: string; acquisitionPurpose: AcquisitionPurpose; leaseStatus: LeaseStatus; state: StateTerritory; proposedLoan?: number; }
export interface PurchaserProfile { purchaserType: PurchaserStructure; borrowerEntityName?: string; corporateTrustee?: 'yes' | 'no' | 'notApplicable'; guaranteesAvailable?: TriState; relatedPartyTenant?: boolean; gstRegistered?: TriState; availableCashEquity: number; sponsorLiquidity: number; liquidityMultiplier: number; existingBusinessDebts?: number; existingBusinessEbitda?: number; existingRentPaid?: number; proposedRentPayable?: number; trusteeDetails?: string; smsfBalance?: number; memberContributions?: number; lrbaRequired?: TriState; bareTrustRequired?: TriState; smsfRelatedPartyTenant?: TriState; smsfSpecialistReviewRequired?: boolean; }
export interface PropertyValuation { purchasePrice: number; estimatedMarketValue: number; bankValuation?: number; useConservativeValuation: boolean; landArea?: number; buildingArea?: number; lettableArea?: number; marketRentPerSqm?: number; passingRentPerSqm?: number; estimatedCapRate?: number; valuationConfidence: 'low' | 'medium' | 'high'; siteCoverageRatio?: number; clearanceHeight?: number; rollerDoors?: number; rollerDoorHeight?: number; dockAccess?: boolean; onGradeLoading?: boolean; hardstandYardArea?: number; hardstandCondition?: 'unknown' | 'good' | 'average' | 'poor'; truckAccessQuality?: 'poor' | 'average' | 'good' | 'excellent'; bDoubleAccess?: TriState; powerCapacity?: 'unknown' | 'singlePhase' | 'threePhase' | 'highCapacity' | 'substationPresent'; slabCondition?: 'unknown' | 'good' | 'average' | 'poor'; roofCondition?: 'unknown' | 'good' | 'average' | 'poor'; }
export interface IncomeInputs { grossPassingRent: number; otherIncome: number; recoveredOutgoings: number; marketRent: number; vacancyAllowancePct: number; incentivesAdjustment: number; tenantArrearsAdjustment: number; nonRecoverableExpenses: number; councilRates: number; water: number; landTax: number; insurance: number; strataOwnersCorp: number; managementFees: number; repairsMaintenance: number; utilities: number; cleaning: number; security: number; otherExpenses: number; leaseCommencementDate?: string; leaseExpiryDate?: string; wale: number; optionsRemaining?: number; breakClause?: TriState; rentReviewType?: 'cpi' | 'fixedPct' | 'marketReview' | 'turnoverRent' | 'noneUnknown'; tenantCovenant: 'government' | 'nationalTenant' | 'listedCompany' | 'establishedSme' | 'newBusiness' | 'relatedParty' | 'weakUnknown'; bankGuaranteeBond?: number; outgoingsRecoveryPct?: number; fitoutOwnership?: 'landlord' | 'tenant' | 'mixed' | 'unknown'; rentOverMarket: TriState; percentageAboveMarket?: number; noiBasis: NoiBasis; }
export interface AcquisitionCosts { depositPaid: number; stampDuty: number; transferRegistrationFee: number; mortgageRegistrationFee: number; pexaSettlementFee: number; legalConveyancingFee: number; bankLegalFee: number; valuationFee: number; loanApplicationFee: number; buyersAgentFee: number; buildingInspection: number; pestInspection: number; structuralInspection: number; fireComplianceInspection: number; planningZoningReview: number; environmentalReport: number; asbestosReport: number; dueDiligence: number; capexReserve: number; workingCapitalReserve: number; otherAcquisitionCosts: number; gstTreatment: GstTreatment; gstAmount: number; gstClaimable: TriState; gstCashflowRequired: TriState; priceGstBasis?: 'inclusive' | 'exclusive' | 'unknown'; vendorGstRegistered?: TriState; purchaserGstRegistered?: TriState; goingConcernConfirmed?: TriState; estimatedGstRefundTiming?: 'atSettlement' | 'oneToThreeMonths' | 'threePlusMonths' | 'unknown'; dutiableValue?: number; foreignPurchaser?: TriState; landholderAcquisition?: TriState; vicCommercialIndustrialPropertyTax?: TriState; saQualifyingNonResidentialLand?: TriState; solicitorConfirmedDuty?: TriState; dutyNotes?: string; capexMode?: CapexMode; manualCapexItems?: Record<string, number>; minimumPostSettlementLiquidityReserve?: number; requiredDebtServiceReserveMonths?: number; requiredOutgoingsReserveMonths?: number; }
export interface LendingAssumptions { profile: LenderPolicyProfileKey; contractInterestRatePct: number; assessmentBufferPct: number; assessmentFloorRatePct?: number; assessmentRateOverridePct?: number; assessmentBasis?: AssessmentBasis; repaymentType?: RepaymentType; exitStrategy?: ExitStrategy; balloonResidualBalance?: number; disablePiDscrTest?: boolean; loanTermYears: number; interestOnlyPeriodYears: number; facilityTermYears?: number; amortisationYears: number; maxLvr: number; hardMaxLvr?: number; minIcr: number; minDscr: number; minDebtYield: number; debtYieldEnabled: boolean; sponsorUpliftAllowed?: boolean; maxOngoingLvrCovenant?: number; minOngoingIcrCovenant?: number; minOngoingDscrCovenant?: number; minWaleCovenant?: number; annualValuationRequired?: boolean; annualFinancialReportingRequired?: boolean; cashReserveCovenant?: boolean; }
export interface BusinessServicingInputs { businessRevenue?: number; ebitda?: number; netProfitBeforeTax?: number; addbacks?: number; directorWagesDrawings?: number; taxProvision?: number; existingRentPaid?: number; proposedRentPayable?: number; existingBusinessDebtRepayments?: number; equipmentFinanceRepayments?: number; vehicleFinanceRepayments?: number; overdraftLimit?: number; overdraftUsed?: number; creditCardLimits?: number; taxDebtAtoPaymentPlans?: number; workingCapitalRequirement?: number; businessCashReserves?: number; basAvailable?: TriState; financialStatementsAvailable?: TriState; taxReturnsAvailable?: TriState; directorGuaranteesAvailable?: TriState; }
export interface GroupDebtInputs { existingCommercialDebt?: number; existingResidentialDebt?: number; existingBusinessDebt?: number; equipmentFinance?: number; vehicleFinance?: number; overdrafts?: number; creditCards?: number; directorGuarantees?: number; directorGuaranteesKnown?: TriState; intercompanyLoans?: number; relatedPartyDebts?: number; atoPaymentPlans?: number; otherLiabilities?: number; existingAnnualDebtService?: number; annualInterestExpense?: number; cashReserves?: number; }
export interface RiskInputs { tenantStrength?: 'strong' | 'established' | 'weak' | 'unknown'; vacancyLevel?: 'none' | 'minor' | 'major'; rentComparedToMarket?: 'belowOrAtMarket' | 'moderatelyOver' | 'materiallyOver' | 'unknown'; incentivesSideAgreements?: TriState; outgoingsRecovery?: 'full' | 'partial' | 'unknown'; locationQuality?: 'good' | 'average' | 'poor'; buildingCondition?: 'good' | 'average' | 'poor'; zoningCertainty?: 'clear' | 'uncertain' | 'notPermitted'; arrears?: TriState; leaseDocumentationComplete?: TriState; fireCompliance?: TriState; environmentalRisk?: 'low' | 'unknown' | 'present' | 'knownContamination'; asbestosRisk?: 'low' | 'unknown' | 'likely' | 'confirmed'; tradeWasteRequirements?: TriState; dangerousGoodsUse?: TriState; specialisedImprovements?: TriState; tenantOperatorSpecialisation?: TriState; makeGoodObligations?: TriState; capexRequired?: 'none' | 'some' | 'heavy'; }
export interface BorrowingInputs { dealProfile: DealProfile; purchaserStructure: PurchaserProfile; propertyValuation: PropertyValuation; income: IncomeInputs; acquisitionCosts: AcquisitionCosts; lendingAssumptions: LendingAssumptions; riskInputs: RiskInputs; businessServicing?: BusinessServicingInputs; groupDebt?: GroupDebtInputs; }
export interface NoiResult { potentialGrossIncome: number; vacancyLoss: number; effectiveGrossIncome: number; totalOperatingExpenses: number; actualNoi: number; stabilisedNoi: number; lenderAdjustedNoi: number; selectedNoi: number; adjustments: string[]; }
export interface AssessmentRateResult { contractRatePct: number; bufferPct: number; floorRatePct: number; assessmentRatePct: number; assessmentBasis: AssessmentBasis; helpNote: string; }
export interface RiskOverlayResult { level: RiskLevel; score: number; noiHaircutPct: number; lvrAdjustmentPct: number; icrAdjustment: number; dscrAdjustment: number; debtYieldAdjustment: number; additionalCapexReserve: number; warnings: string[]; specialistReview: boolean; riskAdjustedAssetCap?: number; commercialRisk?: CommercialRiskResult; industrialRisk?: IndustrialRiskResult; }
export interface FundsToCompleteResult { totalAcquisitionCosts: number; acquisitionCostLineItems?: Record<string, number>; gstCashflowRequirement: number; totalCostBase: number; requiredEquity: number; equitySurplusShortfall: number; capexReserve: number; postSettlementLiquidity: number; monthlyDebtService: number; monthlyOwnerBorneOutgoings: number; monthsDebtServiceCovered: number | null; monthsOutgoingsCovered: number | null; minimumLiquidityRequirement: number; liquiditySurplusShortfall: number; liquidityStatus: 'strong' | 'acceptable' | 'tight' | 'insufficient'; gst: GstResult; warnings: string[]; }
export interface GstResult { economicCost: number; settlementCashflowRequirement: number; claimableAmount: number; timingRisk: 'low' | 'medium' | 'high' | 'unknown'; status: 'green' | 'amber' | 'red' | 'specialistReview'; warnings: string[]; }
export interface BusinessServicingResult { required: boolean; normalisedBusinessCashflow: number; rentReplacementBenefit: number; totalExistingBusinessDebtService: number; businessDebtServiceAvailable: number; businessDscr: number; combinedPropertyBusinessDscr: number; status: 'strong' | 'acceptable' | 'tight' | 'notSupportable' | 'documentsRequired'; verified: boolean; sponsorUpliftEligible: boolean; warnings: string[]; }
export interface GroupDebtResult { totalExistingDebt: number; totalExistingAnnualDebtService: number; totalProposedDebt: number; totalGroupDebtAfterAcquisition: number; netDebtAfterCashReserves: number; debtToEbitda: number | null; interestCover: number; businessDscr: number; groupDscr: number; liquidityCoverageRatio: number; warnings: string[]; }
export interface CapexReserveResult { manualCapexReserve: number; autoCapexReserve: number; totalCapexReserve: number; categories: Array<{ name: string; manual: number; auto: number; total: number }>; warnings: string[]; }
export interface CovenantPressureResult { lvrHeadroom: number; icrHeadroom: number; dscrHeadroom: number; debtYieldHeadroom: number; waleCovenantRisk: string; status: 'low' | 'moderate' | 'high' | 'critical'; warnings: string[]; }
export interface RepaymentTestingResult { ioAnnualInterest: number; piAnnualDebtService: number; residualTermAnnualDebtService: number; ioIcr: number; piDscr: number; residualTermDscr: number; refinanceRiskFlag: string; maturityRiskFlag: string; warnings: string[]; }
export interface BaseRiskAdjustedCriteria { baseMaxLvr: number; lvrRiskAdjustment: number; finalMaxLvrUsed: number; baseMinimumIcr: number; icrRiskAdjustment: number; finalMinimumIcrUsed: number; baseMinimumDscr: number; dscrRiskAdjustment: number; finalMinimumDscrUsed: number; baseMinimumDebtYield: number; debtYieldRiskAdjustment: number; finalMinimumDebtYieldUsed: number; actualNoi: number; stabilisedNoi: number; lenderAdjustedNoi: number; noiHaircutAmount: number; noiHaircutPercentage: number; }
export interface ReverseCalculatorResult { requiredNoiForProposedLoan: number; requiredEquityForCurrentPurchasePrice: number; maximumPurchasePriceBasedOnAvailableEquity: number; requiredValuationToMeetLvr: number; requiredRateToPassIcrPct: number; requiredPriceReduction: number; indicativeEquityGapPriceReductionEquivalent: number; requiredPurchasePriceToFitAvailableEquity: number; requiredRentIncrease: number; requiredAdditionalSponsorLiquidity: number; practicalFixes: string[]; }
export interface WarningGroups { financial: string[]; data: string[]; asset: string[]; structure: string[]; lender: string[]; gstDuty: string[]; specialistReview: string[]; }
export interface CommentarySections { borrowingOutcome: string; creditAssessment: string; purchaseAbility: string; bindingConstraintExplanation: string; assetSpecificRisk: string; borrowerStructureRisk: string; gstAndAcquisitionCostRisk: string; missingInformation: string; recommendedNextAction: string; fixTheDealSummary?: string; }
export interface CommercialRiskResult { leaseQualityScore: number; tenantCovenantScore: number; marketRentRisk: string; leaseExpiryRisk: string; lenderAdjustedNoiBridge: string[]; warnings: string[]; }
export interface IndustrialRiskResult { industrialUsabilityScore: number; environmentalRiskStatus: string; asbestosRiskStatus: string; technicalAssetRisk: string; industrialCapexReserve: number; industrialValuationConfidence: string; warnings: string[]; }
export interface BorrowingResult { propertyValueUsedForLvr: number; propertySupportedLoan: number; sponsorSupportedUplift: number; finalRiskAdjustedLoan: number; proposedLoan: number; loanSupportabilityGap: number; proposedLoanSupportabilityMessage: string; creditAssessmentStatus: CreditAssessmentStatus; purchaseAbilityStatus: PurchaseAbilityStatus; overallStatus: RiskRating; riskRating: RiskRating; bindingConstraint: BindingConstraint; impliedLvr: number; assessmentRate: number; assessmentRateEngine: AssessmentRateResult; icr: number; dscr: number; debtYield: number; annualInterest: number; annualDebtService: number; componentCaps: { lvrCap: number; icrCap: number; dscrCap: number; debtYieldCap: number; liquidityCap: number | null; riskAdjustedCap: number | null; }; baseRiskAdjustedCriteria: BaseRiskAdjustedCriteria & { lvrAdjustmentDriver?: string; icrAdjustmentDriver?: string; dscrAdjustmentDriver?: string; debtYieldAdjustmentDriver?: string; noiHaircutDriver?: string; }; noi: NoiResult; fundsToComplete: FundsToCompleteResult; businessServicing: BusinessServicingResult; groupDebt: GroupDebtResult; capexReserve: CapexReserveResult; covenantPressure: CovenantPressureResult; repaymentTesting: RepaymentTestingResult; reverseCalculators: ReverseCalculatorResult; warningGroups: WarningGroups; purchaseAbilityStatusLabel: string; creditAssessmentStatusLabel: string; primaryReason: string; secondaryRisks: string[]; requiredNextAction: string; warnings: string[]; documentChecklist: string[]; commentary: string; commentarySections: CommentarySections; scenarios: Array<{ name: string; maxLoan: number; proposedLoanSupportability: string; impliedLvr: number; icr: number; dscr: number; debtYield: number; requiredEquity: number; equitySurplusShortfall: number; creditAssessmentStatus: CreditAssessmentStatus; purchaseAbilityStatus: PurchaseAbilityStatus; riskRating: RiskRating; bindingConstraint: BindingConstraint; explanation?: string; }>; }
