import type { BorrowingInputs, BorrowingResult } from './calculatorTypes';

const money = (n: number) => new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD', maximumFractionDigits: 0 }).format(n || 0);
const constraintLabel: Record<string, string> = { lvr: 'LVR ceiling', icr: 'minimum ICR requirement', dscr: 'minimum DSCR requirement', debtYield: 'minimum debt yield requirement', liquidity: 'sponsor liquidity test', valuation: 'valuation', fundsToComplete: 'funds-to-complete position', riskOverlay: 'risk overlay', specialistReview: 'specialist review trigger', none: 'no supportable loan' };

export function generateCommentary(inputs: BorrowingInputs, result: Omit<BorrowingResult, 'commentary'>): string {
  const constraint = constraintLabel[result.bindingConstraint] ?? result.bindingConstraint;
  const constraintType = result.bindingConstraint === 'lvr' || result.bindingConstraint === 'valuation' ? 'valuation-constrained' : result.bindingConstraint === 'liquidity' ? 'liquidity-constrained' : result.bindingConstraint === 'riskOverlay' || result.bindingConstraint === 'specialistReview' ? 'risk-constrained' : 'income-constrained';
  const ability = result.fundsToComplete.equitySurplusShortfall >= 0 ? `The client appears to have sufficient equity, with an estimated surplus of ${money(result.fundsToComplete.equitySurplusShortfall)}.` : `The client is short on equity by approximately ${money(Math.abs(result.fundsToComplete.equitySurplusShortfall))}.`;
  const industrial = inputs.dealProfile.assetCategory === 'industrial' ? ' This industrial borrowing result is subject to confirmation of key operational and technical matters, including zoning, permitted use, roof and slab condition, power capacity, truck access, fire compliance, environmental risk and asbestos status. These matters can materially affect valuation, lender appetite and required equity contribution.' : '';
  return `Based on the information provided, the asset supports an estimated maximum risk-adjusted loan of ${money(result.finalRiskAdjustedLoan)}. The binding constraint is the ${constraint}, so the transaction is currently ${constraintType}. ${ability} The assessment uses ${inputs.income.noiBasis.replace(/([A-Z])/g, ' $1').toLowerCase()} NOI, an assessment rate of ${(result.assessmentRate * 100).toFixed(2)}%, maximum LVR of ${(inputs.lendingAssumptions.maxLvr * 100).toFixed(0)}%, minimum ICR of ${inputs.lendingAssumptions.minIcr.toFixed(2)}x, minimum DSCR of ${inputs.lendingAssumptions.minDscr.toFixed(2)}x and debt yield of ${(inputs.lendingAssumptions.minDebtYield * 100).toFixed(1)}%. The purchase status is ${result.purchaseAbilityStatus.replace(/([A-Z])/g, ' $1').toLowerCase()}. Key next steps are to verify the lease, valuation, GST treatment, purchaser structure, available equity and the first due-diligence documents: ${result.documentChecklist.slice(0, 5).join(', ')}.${industrial}`;
}
