import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, Building2, ExternalLink, FileText, Globe2, Loader2, Newspaper, RefreshCw, Search, Settings, ShieldCheck, Sparkles, TrendingUp } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { answerMarketUpdateQuestion, fetchLatestMarketDigest, fetchMarketSourceHealth, fetchMarketSources, fetchMarketUpdates, generateMarketDigest24h } from '@/services/marketUpdatesService';
import type { MarketAudienceTag, MarketDigest24h, MarketGeography, MarketImpactLevel, MarketQAMessage, MarketSource, MarketSourceHealth, MarketUpdate, MarketUpdateCategory } from '@/types/marketUpdates';

const categories: Array<'all' | MarketUpdateCategory> = ['all','finance','property_market','construction','policy_regulation','rental_market','economy','political','planning_supply','other'];
const geographies: Array<'all' | MarketGeography> = ['all','Australia','NSW','VIC','QLD','WA','SA','TAS','ACT','NT','Multi'];
const impacts: Array<'all' | MarketImpactLevel> = ['all','high','medium','low'];
const audiences: Array<'all' | MarketAudienceTag> = ['all','investors','owner_occupiers','first_home_buyers','smsf','developers','buyers_agents','mortgage_brokers','property_managers','builders','finance_brokers'];
const label = (value: string) => value === 'all' ? 'All' : value.split('_').map((part) => part[0].toUpperCase() + part.slice(1)).join(' ');
const dateLabel = (v?: string | null) => v ? new Date(v).toLocaleString('en-AU', { dateStyle: 'medium', timeStyle: 'short' }) : 'Not available';

export default function MarketUpdates() {
  const navigate = useNavigate();
  const [updates, setUpdates] = useState<MarketUpdate[]>([]);
  const [sources, setSources] = useState<MarketSource[]>([]);
  const [sourceHealth, setSourceHealth] = useState<MarketSourceHealth>({ totalSources:0, enabledSources:0, failedSources:0 });
  const [loading, setLoading] = useState(true);
  const [digestLoading, setDigestLoading] = useState(false);
  const [digest, setDigest] = useState<MarketDigest24h | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [selectedUpdate, setSelectedUpdate] = useState<MarketUpdate | null>(null);
  const [qaUpdate, setQaUpdate] = useState<MarketUpdate | null>(null);
  const [question, setQuestion] = useState('');
  const [qaMessage, setQaMessage] = useState<MarketQAMessage | null>(null);
  const [filters, setFilters] = useState({ category: 'all', geography: 'all', impact: 'all', audience: 'all' });

  const loadWorkspace = async () => { setLoading(true); setMessage(null); const [u,d,s,h] = await Promise.all([fetchMarketUpdates(), fetchLatestMarketDigest(), fetchMarketSources(), fetchMarketSourceHealth()]); setUpdates(u); setDigest(d); setSources(s); setSourceHealth(h); setLoading(false); };
  useEffect(() => { void loadWorkspace(); }, []);

  const filteredUpdates = useMemo(() => updates.filter((u) => (filters.category === 'all' || u.category === filters.category) && (filters.geography === 'all' || u.geography.includes(filters.geography as MarketGeography)) && (filters.impact === 'all' || u.impact_level === filters.impact) && (filters.audience === 'all' || u.audience_tags.includes(filters.audience as MarketAudienceTag))), [filters, updates]);
  const kpis = useMemo(() => { const today = new Date().toDateString(); return [
    { label:'Updates Today', value: updates.filter(u => new Date(u.ingested_at).toDateString() === today).length, icon: Newspaper },
    { label:'High Impact', value: updates.filter(u => u.impact_level === 'high').length, icon: TrendingUp },
    { label:'Finance & Lending', value: updates.filter(u => u.category === 'finance').length, icon: BarChart3 },
    { label:'Property Market', value: updates.filter(u => u.category === 'property_market').length, icon: Building2 },
    { label:'Policy / Regulation', value: updates.filter(u => u.category === 'policy_regulation').length, icon: ShieldCheck },
    { label:'Construction & Supply', value: updates.filter(u => u.category === 'construction' || u.category === 'planning_supply').length, icon: Activity },
  ]; }, [updates]);
  const highImpact = updates.filter(u => u.impact_level === 'high').slice(0, 4);

  const handleDigest = async () => { setDigestLoading(true); const result = await generateMarketDigest24h(); setMessage(result.message); setDigest(result.digest ?? await fetchLatestMarketDigest()); setDigestLoading(false); };
  const handleAsk = async () => { if (!question.trim()) return; setQaMessage(await answerMarketUpdateQuestion(question, qaUpdate ? [qaUpdate.id] : undefined)); };

  return <main className="min-h-screen bg-slate-950 text-slate-100"><div className="mx-auto w-full max-w-[1600px] space-y-6 px-4 py-6 md:px-8">
    <section className="w-full overflow-hidden rounded-[2rem] border border-cyan-400/20 bg-gradient-to-br from-slate-900 via-slate-950 to-indigo-950 p-6 shadow-2xl shadow-cyan-950/30 md:p-8">
      <div className="flex flex-col gap-6 xl:flex-row xl:items-center xl:justify-between"><div className="space-y-4"><Badge className="bg-cyan-400/10 text-cyan-200">AI MARKET INTELLIGENCE</Badge><h1 className="text-4xl font-bold tracking-tight md:text-5xl">Market Updates</h1><p className="max-w-4xl text-base text-slate-300 md:text-lg">Source-backed Australian property, finance, construction, rental, policy and economic intelligence in one report-ready workspace.</p><div className="flex flex-wrap gap-2 text-xs text-slate-400"><Badge variant="outline">Last success: {dateLabel(sourceHealth.lastSuccessAt)}</Badge><Badge variant="outline">Coverage: Australia-wide</Badge><Badge variant="outline">Refresh cycle: 24 hours</Badge></div></div>
        <div className="flex flex-wrap gap-2"><Button onClick={loadWorkspace}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button><Button onClick={handleDigest} disabled={digestLoading}>{digestLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}Generate 24h Digest</Button><Button disabled variant="outline" title="Export available after digest generation."><FileText className="mr-2 h-4 w-4" />Export Summary</Button><Button variant="outline" onClick={() => navigate('/sources')}><Settings className="mr-2 h-4 w-4" />Sources</Button></div></div>
    </section>
    {message && <Card className="border-cyan-400/20 bg-cyan-950/20"><CardContent className="p-4 text-cyan-100">{message}</CardContent></Card>}
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6">{kpis.map((kpi) => <Card key={kpi.label} className="border-white/10 bg-white/[0.04] text-slate-100"><CardContent className="p-5"><kpi.icon className="mb-4 h-5 w-5 text-cyan-300" /><div className="text-3xl font-semibold">{kpi.value}</div><p className="text-xs text-slate-400">{kpi.label}</p></CardContent></Card>)}</section>
    <section className="grid gap-3 rounded-3xl border border-white/10 bg-white/[0.03] p-4 md:grid-cols-4">{([['category',categories],['geography',geographies],['impact',impacts],['audience',audiences]] as const).map(([key, values]) => <div key={key} className="space-y-2"><Label>{label(key)}</Label><Select value={(filters as any)[key]} onValueChange={(value) => setFilters(f => ({ ...f, [key]: value }))}><SelectTrigger className="border-white/10 bg-slate-950/70"><SelectValue /></SelectTrigger><SelectContent>{(values as readonly string[]).map(value => <SelectItem key={value} value={value}>{key === 'impact' && value === 'all' ? 'All Impact' : key === 'audience' && value === 'all' ? 'All Audiences' : label(value)}</SelectItem>)}</SelectContent></Select></div>)}</section>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px] 2xl:grid-cols-[minmax(0,1fr)_400px]"><div className="space-y-6">
      <Card className="border-purple-400/20 bg-slate-900/80 text-slate-100"><CardHeader><CardTitle>Daily Market Digest</CardTitle></CardHeader><CardContent>{digest ? <div className="space-y-3"><p>{digest.executive_summary}</p><div className="flex flex-wrap gap-2">{digest.source_urls.slice(0,4).map(url => <Badge key={url} variant="outline">Source cited</Badge>)}</div></div> : <p className="text-slate-400">No source-backed updates were found in the last 24 hours.</p>}</CardContent></Card>
      <Card className="border-white/10 bg-slate-900/80 text-slate-100"><CardHeader><CardTitle>Source-backed Update Cards</CardTitle></CardHeader><CardContent className="space-y-4">{loading ? <p>Loading market workspace…</p> : filteredUpdates.length === 0 ? <div className="rounded-2xl border border-dashed border-cyan-300/30 bg-cyan-950/10 p-10 text-center"><Globe2 className="mx-auto mb-3 h-10 w-10 text-cyan-300" /><h2 className="text-xl font-semibold">No source-backed market updates have been ingested yet</h2><p className="mx-auto mt-2 max-w-2xl text-slate-400">Configure enabled sources and run the 24-hour ingestion job to begin. This workspace will remain empty rather than showing fake market news.</p><div className="mt-5 flex justify-center gap-2"><Button variant="outline" onClick={() => navigate('/sources')}>Sources</Button><Button variant="ghost" onClick={() => window.open('/docs/market-updates-phase-2.md','_blank')}>View Setup Guide</Button></div></div> : filteredUpdates.map(update => <article key={update.id} className="rounded-2xl border border-white/10 bg-slate-950/40 p-5"><div className="flex flex-wrap gap-2"><Badge>{label(update.category)}</Badge><Badge variant="outline">Impact: {label(update.impact_level)}</Badge>{update.geography.map(geo => <Badge key={geo} variant="secondary">{geo}</Badge>)}</div><h3 className="mt-3 text-xl font-semibold">{update.title}</h3><p className="text-sm text-slate-400">{update.source_name} · {dateLabel(update.source_published_at ?? update.ingested_at)}</p><p className="mt-3 text-slate-200">{update.ai_summary ?? 'Summary awaiting source-grounded AI processing.'}</p><p className="mt-2 text-sm text-slate-300"><strong>Why it matters:</strong> {update.why_it_matters ?? 'Implications will appear once summarisation is connected.'}</p><div className="mt-3 flex flex-wrap gap-1">{update.citation_urls.map(url => <Badge key={url} variant="outline" className="border-cyan-300/30 text-cyan-200">Citation</Badge>)}</div><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={() => setSelectedUpdate(update)}>Open Analysis</Button><Button size="sm" variant="outline" onClick={() => setQaUpdate(update)}>Ask AI</Button><Button asChild size="sm" variant="ghost"><a href={update.source_url} target="_blank" rel="noreferrer">Source <ExternalLink className="ml-1 h-3 w-3" /></a></Button></div></article>)}</CardContent></Card></div>
      <aside className="space-y-4"><Card className="border-white/10 bg-white/[0.04] text-slate-100"><CardHeader><CardTitle>Category Breakdown</CardTitle></CardHeader><CardContent className="space-y-2">{categories.filter(c => c !== 'all').map(cat => <div key={cat} className="flex justify-between text-sm"><span>{label(cat)}</span><span>{updates.filter(u => u.category === cat).length}</span></div>)}</CardContent></Card><Card className="border-white/10 bg-white/[0.04] text-slate-100"><CardHeader><CardTitle>High Impact Watchlist</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-300">{highImpact.length ? highImpact.map(u => <button key={u.id} onClick={() => setSelectedUpdate(u)} className="block w-full rounded-lg border border-white/10 p-2 text-left hover:border-cyan-300/30">{u.title}</button>) : 'No high impact sourced updates yet.'}</CardContent></Card><Card className="border-white/10 bg-white/[0.04] text-slate-100"><CardHeader><CardTitle>Ask AI about market updates</CardTitle></CardHeader><CardContent className="space-y-3"><Search className="h-5 w-5 text-cyan-300" /><p className="text-sm text-slate-400">{updates.length ? 'Ask source-grounded questions about published updates only.' : 'Market Q&A will activate once source-backed updates are available.'}</p><Textarea value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask about sourced market updates…" disabled={!updates.length} /><Button size="sm" onClick={handleAsk} disabled={!updates.length || !question.trim()}>Ask safely</Button>{qaMessage && <p className="rounded-lg bg-slate-950/60 p-3 text-sm">{qaMessage.content}</p>}</CardContent></Card><Card className="border-white/10 bg-white/[0.04] text-slate-100"><CardHeader><CardTitle>Source Health</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-300"><div className="grid grid-cols-3 gap-2 text-center"><div><b>{sourceHealth.totalSources}</b><p className="text-xs text-slate-500">Total</p></div><div><b>{sourceHealth.enabledSources}</b><p className="text-xs text-slate-500">Enabled</p></div><div><b>{sourceHealth.failedSources}</b><p className="text-xs text-slate-500">Failed</p></div></div><p>Last fetched: {dateLabel(sourceHealth.lastFetchedAt)}</p><p>Last success: {dateLabel(sourceHealth.lastSuccessAt)}</p>{sourceHealth.lastError ? <p className="text-amber-200"><AlertTriangle className="mr-1 inline h-4 w-4" />{sourceHealth.lastError}</p> : <p className="text-slate-400">{sources.length ? 'No source errors reported.' : 'Source registry ready. No enabled sources connected yet.'}</p>}</CardContent></Card></aside></section>
    <p className="pb-6 text-xs text-slate-500">General market intelligence only. Review source material and obtain professional advice before acting.</p>
    <Dialog open={Boolean(selectedUpdate)} onOpenChange={(open) => !open && setSelectedUpdate(null)}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>{selectedUpdate?.title}</DialogTitle></DialogHeader><div className="space-y-4 text-sm"><p><strong>Source:</strong> <a className="text-cyan-500" href={selectedUpdate?.source_url} target="_blank" rel="noreferrer">{selectedUpdate?.source_name}</a></p><p><strong>Published:</strong> {dateLabel(selectedUpdate?.source_published_at)}</p><p><strong>AI summary:</strong> {selectedUpdate?.ai_summary ?? 'Awaiting source-grounded analysis.'}</p>{Boolean(selectedUpdate?.key_points?.length) && <ul className="list-disc pl-5">{selectedUpdate?.key_points.map(p => <li key={p}>{p}</li>)}</ul>}<p><strong>Why it matters:</strong> {selectedUpdate?.why_it_matters ?? 'Not available yet.'}</p><p><strong>Property implications:</strong> {selectedUpdate?.property_implications ?? 'Not available yet.'}</p><p><strong>Finance implications:</strong> {selectedUpdate?.finance_implications ?? 'Not available yet.'}</p><p><strong>Policy implications:</strong> {selectedUpdate?.policy_implications ?? 'Not available yet.'}</p><p><strong>Risk flags:</strong> {selectedUpdate?.risk_flags?.join(', ') || 'Not available yet.'}</p><p><strong>Confidence:</strong> {selectedUpdate?.confidence_score ?? 0}%</p><p><strong>Citations:</strong> {selectedUpdate?.citation_urls?.map(url => <a key={url} className="ml-2 text-cyan-500" href={url} target="_blank" rel="noreferrer">Open source</a>)}</p></div></DialogContent></Dialog>
    <Dialog open={Boolean(qaUpdate)} onOpenChange={(open) => { if (!open) { setQaUpdate(null); setQaMessage(null); } }}><DialogContent><DialogHeader><DialogTitle>Ask AI about this update</DialogTitle></DialogHeader><Label htmlFor="market-question">Question</Label><Textarea id="market-question" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask a source-grounded question…" /><Button onClick={handleAsk}>Ask safely</Button><p className="text-sm text-slate-500">{qaMessage?.content ?? 'Answers are limited to ingested, published market updates with citations.'}</p>{qaMessage?.citations.map(url => <a key={url} className="block text-sm text-cyan-600" href={url} target="_blank" rel="noreferrer">Citation</a>)}</DialogContent></Dialog>
  </div></main>;
}
