/**
 * Phase 9 — Multi-service dispatch.
 *
 * Adds non-Docling providers so the orchestrator can route imports across
 * heterogeneous backends:
 *
 *   - `renderSourceProvider` — wraps the `render-source` edge function for
 *     code/URL inputs (HTML/CSS/JSX/repo zips / live URLs). When handed a raw
 *     PDF it declares itself unsupported, so the dispatcher falls through to
 *     Docling. Returns a minimal `ImportResult` shape so the rest of the
 *     pipeline (CDIR/fidelity/repair) can treat it identically.
 *   - `weasyprintReverseProvider` — last-resort fallback that re-renders the
 *     source via the WeasyPrint sidecar to a normalised PDF and re-imports
 *     through Docling. Useful when the original PDF is structurally broken
 *     (e.g. generated by a buggy exporter) — WeasyPrint normalises it.
 *
 * Both providers are pure adapters over existing edge functions; no schema
 * changes. They participate in the Phase 7 registry via `registerFallbackProvider`.
 */
import type { ImportOptions, ImportResult } from '../types';
import type { ImportProvider } from './index';
import { extractPdfViaDocling } from '../extractPdfViaDocling';
import { invokeSecureFunction, describeAuthError } from '@/lib/secureInvoke';

// ---------------------------------------------------------------------------
// render-source
// ---------------------------------------------------------------------------

/** PDFs always have these magic bytes; cheap pre-flight. */
function looksLikePdf(file: File): boolean {
  if (file.type === 'application/pdf') return true;
  return /\.pdf$/i.test(file.name ?? '');
}

export const renderSourceProvider: ImportProvider = {
  id: 'render-source',
  label: 'Render-Source (HTML/Code → raster)',
  engine: 'render-source',
  recoverableFailures: ['timeout', 'parser_error', 'network', 'rate_limited'],
  supports: (file) => !looksLikePdf(file),
  async run(file, opts): Promise<ImportResult> {
    const arrayBuf = await file.arrayBuffer();
    const bytes = new Uint8Array(arrayBuf);
    // base64 encode in chunks (keeps large files off the stack).
    const CHUNK = 0x8000;
    let bin = '';
    for (let i = 0; i < bytes.length; i += CHUNK) {
      bin += String.fromCharCode.apply(null, Array.from(bytes.subarray(i, i + CHUNK)));
    }
    const sourceBase64 = btoa(bin);

    const { data, error } = await invokeSecureFunction(
      'render-source',
      {
        operation: 'render',
        source_base64: sourceBase64,
        source_name: file.name,
        source_type: file.type,
        mode: opts.mode,
        dpi: opts.rasterDpi ?? 150,
      },
      { timeoutMs: 300_000 },
    );
    if (error) throw new Error(describeAuthError(error.message) ?? error.message ?? 'render-source failed');
    if (!data || (data as any).error) {
      throw new Error(String((data as any)?.error ?? 'render-source returned no payload'));
    }

    const payload = data as {
      template?: { id: string; name: string };
      import_id?: string;
      page_count?: number;
    };
    if (!payload.template?.id || !payload.import_id) {
      throw new Error('render-source returned an incomplete result');
    }

    return {
      template: payload.template,
      importId: payload.import_id,
      pageCount: payload.page_count ?? 0,
      engine: 'docling', // pipeline treats output identically; tagged via attempt audit
      fidelityReport: {
        semanticPages: payload.page_count ?? 0,
        rasterizedPages: 0,
        textBlocks: 0,
        images: 0,
        vectors: 0,
        fontsEmbedded: 0,
        fontsSubstituted: [],
      },
    };
  },
};

// ---------------------------------------------------------------------------
// WeasyPrint reverse-render fallback
// ---------------------------------------------------------------------------

/**
 * When Docling rejects a structurally-broken PDF, we can sometimes salvage it
 * by extracting its rendered pages as images, wrapping them in a minimal HTML
 * document, and re-rendering through WeasyPrint — producing a clean PDF that
 * Docling can then parse. This provider performs that loop in one call.
 *
 * The actual WeasyPrint round-trip is delegated to the `template-import-pdf`
 * edge function via the `reverse_render_then_import` operation (added in
 * Phase 9). If that op is not yet deployed, the function returns
 * `{ error: 'unsupported' }` and the orchestrator skips this provider.
 */
export const weasyprintReverseProvider: ImportProvider = {
  id: 'weasyprint-reverse',
  label: 'WeasyPrint reverse-render → Docling',
  engine: 'docling',
  recoverableFailures: ['timeout', 'parser_error', 'invalid_pdf', 'network'],
  supports: (file) => looksLikePdf(file),
  async run(file, opts): Promise<ImportResult> {
    const arrayBuf = await file.arrayBuffer();
    const bytes = new Uint8Array(arrayBuf);
    const CHUNK = 0x8000;
    let bin = '';
    for (let i = 0; i < bytes.length; i += CHUNK) {
      bin += String.fromCharCode.apply(null, Array.from(bytes.subarray(i, i + CHUNK)));
    }
    const sourceBase64 = btoa(bin);

    const { data, error } = await invokeSecureFunction(
      'template-import-pdf',
      {
        operation: 'reverse_render_then_import',
        source_base64: sourceBase64,
        source_name: file.name,
        mode: opts.mode,
      },
      { timeoutMs: 600_000 },
    );
    if (error) throw new Error(describeAuthError(error.message) ?? error.message ?? 'weasyprint-reverse failed');
    const payload = data as {
      error?: string;
      normalised_url?: string;
      normalised_name?: string;
    };
    if (payload?.error) {
      // Surface "unsupported" so the registry knows to skip rather than retry.
      throw new Error(payload.error);
    }
    if (!payload?.normalised_url) {
      throw new Error('weasyprint-reverse produced no normalised PDF');
    }

    // Re-import the cleaned PDF via Docling.
    const cleanRes = await fetch(payload.normalised_url);
    const cleanBlob = await cleanRes.blob();
    const cleanFile = new File([cleanBlob], payload.normalised_name ?? `normalised-${file.name}`, {
      type: 'application/pdf',
    });
    return extractPdfViaDocling(cleanFile, opts);
  },
};
