/**
 * pdfImportMonitoringRules — Phase 9F monitoring rule catalog + thresholds.
 *
 * One rule per signal code, defining its domain, default severity, owner,
 * recovery actions (aligned with the Phase 8F triage vocabulary), whether it
 * blocks release, and its runbook anchor. Plus the default thresholds and
 * lookup helpers. Pure data — no I/O.
 */
import type {
  PdfImportMonitoringAction,
  PdfImportMonitoringRule,
  PdfImportMonitoringSignalCode,
  PdfImportMonitoringThresholds,
} from './pdfImportMonitoringTypes';

export const DEFAULT_PDF_IMPORT_MONITORING_THRESHOLDS: PdfImportMonitoringThresholds = {
  failedImportsError: 1,
  failedImportsCritical: 3,
  stuckImportsError: 1,
  diagnosticsJobsFailedError: 1,
  missingVisualQaWarning: 1,
  missingRepairAuditWarning: 1,
  exportParityFailedError: 1,
  goldenGateFailedCritical: 1,
  baselineDegradedWarning: 1,
  manualReviewRateWarning: 0.5,
  corpusCoverageExpected: 6,
  backendUnknownOperationCritical: 1,
  privateArtifactRiskCritical: 1,
};

export const PDF_IMPORT_MONITORING_RULES: PdfImportMonitoringRule[] = [
  {
    code: 'failed_imports_recent',
    domain: 'import_pipeline',
    severity: 'error',
    owner: 'developer_fullstack',
    primaryAction: 'inspect_template_imports',
    secondaryActions: ['inspect_pdf_import_jobs', 'inspect_supabase_function_logs', 'inspect_cloud_run_logs'],
    releaseBlocking: true,
    title: 'Recent PDF imports failed',
    description: 'One or more PDF imports failed recently.',
    runbookAnchor: 'failed-imports-recent',
  },
  {
    code: 'stuck_imports_recent',
    domain: 'import_pipeline',
    severity: 'error',
    owner: 'developer_backend',
    primaryAction: 'inspect_supabase_function_logs',
    secondaryActions: ['inspect_pdf_import_jobs', 'rerun_import'],
    releaseBlocking: true,
    title: 'PDF imports stuck in progress',
    description: 'One or more PDF imports are stuck in a non-terminal state.',
    runbookAnchor: 'stuck-imports-recent',
  },
  {
    code: 'diagnostics_jobs_failed',
    domain: 'sidecar_diagnostics',
    severity: 'error',
    owner: 'developer_sidecar',
    primaryAction: 'inspect_cloud_run_logs',
    secondaryActions: ['inspect_pdf_import_jobs', 'patch_sidecar'],
    releaseBlocking: true,
    title: 'PDF diagnostics jobs failed',
    description: 'Docling / sidecar diagnostics jobs failed.',
    runbookAnchor: 'diagnostics-jobs-failed',
  },
  {
    code: 'engine_version_missing',
    domain: 'sidecar_diagnostics',
    severity: 'warning',
    owner: 'developer_backend',
    primaryAction: 'inspect_pdf_import_jobs',
    secondaryActions: ['inspect_supabase_function_logs'],
    releaseBlocking: false,
    title: 'Engine version missing',
    description: 'Completed imports are missing engine version metadata.',
    runbookAnchor: 'engine-version-missing',
  },
  {
    code: 'source_rasters_missing',
    domain: 'artifact_integrity',
    severity: 'error',
    owner: 'developer_backend',
    primaryAction: 'inspect_storage_artifacts',
    secondaryActions: ['rerun_import'],
    releaseBlocking: true,
    title: 'Source rasters missing',
    description: 'Source raster artifacts are missing for imports that should have them.',
    runbookAnchor: 'source-rasters-missing',
  },
  {
    code: 'visual_quality_missing',
    domain: 'visual_quality',
    severity: 'warning',
    owner: 'developer_frontend',
    primaryAction: 'rerun_visual_qa',
    secondaryActions: ['inspect_storage_artifacts', 'review_dashboard'],
    releaseBlocking: false,
    title: 'Visual QA missing',
    description: 'Completed imports are missing Visual QA output.',
    runbookAnchor: 'visual-quality-missing',
  },
  {
    code: 'repair_audit_missing',
    domain: 'repair',
    severity: 'warning',
    owner: 'developer_backend',
    primaryAction: 'rerun_repair',
    secondaryActions: ['inspect_storage_artifacts', 'inspect_supabase_function_logs'],
    releaseBlocking: false,
    title: 'Repair audit missing',
    description: 'Imports with Visual QA are missing a repair audit.',
    runbookAnchor: 'repair-audit-missing',
  },
  {
    code: 'export_parity_missing',
    domain: 'export_parity',
    severity: 'warning',
    owner: 'operator',
    primaryAction: 'rerun_export_parity',
    secondaryActions: ['document_warning'],
    releaseBlocking: false,
    title: 'Export parity missing',
    description: 'Golden-ready imports are missing export parity.',
    runbookAnchor: 'export-parity-missing',
  },
  {
    code: 'export_parity_failed',
    domain: 'export_parity',
    severity: 'error',
    owner: 'developer_frontend',
    primaryAction: 'rerun_export_parity',
    secondaryActions: ['patch_renderer', 'inspect_storage_artifacts'],
    releaseBlocking: true,
    title: 'Export parity failed',
    description: 'Export parity failed or produced invalid output.',
    runbookAnchor: 'export-parity-failed',
  },
  {
    code: 'export_parity_manual_required',
    domain: 'export_parity',
    severity: 'warning',
    owner: 'manual_review',
    primaryAction: 'review_dashboard',
    secondaryActions: ['rerun_export_parity', 'document_warning'],
    releaseBlocking: false,
    title: 'Export parity manual review required',
    description: 'Export parity requires manual review to complete.',
    runbookAnchor: 'export-parity-manual-required',
  },
  {
    code: 'manual_review_rate_high',
    domain: 'visual_quality',
    severity: 'warning',
    owner: 'qa',
    primaryAction: 'review_dashboard',
    secondaryActions: ['run_failure_triage', 'document_warning'],
    releaseBlocking: false,
    title: 'Manual review rate is high',
    description: 'The manual review rate over recent completed imports is above threshold.',
    runbookAnchor: 'manual-review-rate-high',
  },
  {
    code: 'golden_quality_gate_failed',
    domain: 'golden_regression',
    severity: 'critical',
    owner: 'qa',
    primaryAction: 'rerun_golden_regression',
    secondaryActions: ['run_failure_triage', 'block_release'],
    releaseBlocking: true,
    title: 'Golden quality gate failed',
    description: 'Golden regression failed required quality gates.',
    runbookAnchor: 'golden-quality-gate-failed',
  },
  {
    code: 'golden_quality_gate_blocked',
    domain: 'golden_regression',
    severity: 'critical',
    owner: 'operator',
    primaryAction: 'rerun_golden_regression',
    secondaryActions: ['inspect_storage_artifacts', 'block_release'],
    releaseBlocking: true,
    title: 'Golden quality gate blocked',
    description: 'Golden regression quality gates are blocked.',
    runbookAnchor: 'golden-quality-gate-blocked',
  },
  {
    code: 'golden_summary_missing',
    domain: 'golden_regression',
    severity: 'warning',
    owner: 'operator',
    primaryAction: 'rerun_golden_regression',
    secondaryActions: ['document_warning'],
    releaseBlocking: false,
    title: 'Golden regression summary missing',
    description: 'No golden regression summaries are present.',
    runbookAnchor: 'golden-summary-missing',
  },
  {
    code: 'golden_history_missing',
    domain: 'golden_regression',
    severity: 'warning',
    owner: 'operator',
    primaryAction: 'rerun_golden_regression',
    secondaryActions: ['document_warning'],
    releaseBlocking: false,
    title: 'Golden run history missing',
    description: 'No golden run history rows are present.',
    runbookAnchor: 'golden-history-missing',
  },
  {
    code: 'baseline_degraded',
    domain: 'golden_regression',
    severity: 'warning',
    owner: 'qa',
    primaryAction: 'run_failure_triage',
    secondaryActions: ['rerun_golden_regression', 'document_warning'],
    releaseBlocking: false,
    title: 'Golden baseline degraded',
    description: 'The latest golden run is worse than the previous baseline.',
    runbookAnchor: 'baseline-degraded',
  },
  {
    code: 'corpus_coverage_incomplete',
    domain: 'golden_regression',
    severity: 'warning',
    owner: 'qa',
    primaryAction: 'rerun_golden_regression',
    secondaryActions: ['document_warning'],
    releaseBlocking: false,
    title: 'Golden corpus coverage incomplete',
    description: 'One or more canonical corpus items have no history run.',
    runbookAnchor: 'corpus-coverage-incomplete',
  },
  {
    code: 'release_blocked_database',
    domain: 'release_gates',
    severity: 'critical',
    owner: 'developer_fullstack',
    primaryAction: 'run_release_gate_sql',
    secondaryActions: ['block_release', 'run_failure_triage'],
    releaseBlocking: true,
    title: 'Database release gate blocked',
    description: 'The database-side release gate indicates a release-blocking state.',
    runbookAnchor: 'release-blocked-database',
  },
  {
    code: 'backend_unknown_operation',
    domain: 'backend_contract',
    severity: 'critical',
    owner: 'developer_backend',
    primaryAction: 'patch_supabase_function',
    secondaryActions: ['inspect_supabase_function_logs', 'block_release'],
    releaseBlocking: true,
    title: 'Backend unknown operation detected',
    description: 'The frontend attempted an operation the backend does not support.',
    runbookAnchor: 'backend-unknown-operation',
  },
  {
    code: 'private_artifact_risk',
    domain: 'security_privacy',
    severity: 'critical',
    owner: 'security',
    primaryAction: 'block_release',
    secondaryActions: ['document_warning'],
    releaseBlocking: true,
    title: 'Private artifact risk detected',
    description: 'Private artifacts appear to be staged or at risk of exposure.',
    runbookAnchor: 'private-artifact-risk',
  },
];

const RULES_BY_CODE: Record<string, PdfImportMonitoringRule> = Object.fromEntries(
  PDF_IMPORT_MONITORING_RULES.map((rule) => [rule.code, rule]),
);

/** Fallback rule for an unrecognized code (never release-blocking). */
function fallbackRule(code: PdfImportMonitoringSignalCode): PdfImportMonitoringRule {
  return {
    code,
    domain: 'backend_contract',
    severity: 'warning',
    owner: 'unknown',
    primaryAction: 'escalate',
    secondaryActions: ['document_warning'],
    releaseBlocking: false,
    title: 'Unknown monitoring signal',
    description: `No rule is registered for signal code "${code}".`,
    runbookAnchor: 'unknown-signal',
  };
}

export function getPdfImportMonitoringRule(
  code: PdfImportMonitoringSignalCode,
): PdfImportMonitoringRule {
  return RULES_BY_CODE[code] ?? fallbackRule(code);
}

const ACTION_LABELS: Record<PdfImportMonitoringAction, string> = {
  no_action: 'No action',
  review_dashboard: 'Review dashboard',
  run_phase_9f_sql: 'Run Phase 9F monitoring SQL',
  run_release_gate_sql: 'Run Phase 9E release gate SQL',
  inspect_template_imports: 'Inspect template_imports',
  inspect_pdf_import_jobs: 'Inspect pdf_import_jobs',
  inspect_storage_artifacts: 'Inspect storage artifacts',
  inspect_supabase_function_logs: 'Inspect Supabase function logs',
  inspect_cloud_run_logs: 'Inspect Cloud Run logs',
  rerun_import: 'Rerun import',
  rerun_visual_qa: 'Rerun Visual QA',
  rerun_repair: 'Rerun repair',
  rerun_export_parity: 'Rerun export parity',
  rerun_golden_regression: 'Rerun golden regression',
  run_failure_triage: 'Run failure triage',
  patch_frontend: 'Patch frontend',
  patch_supabase_function: 'Patch Supabase function',
  patch_sidecar: 'Patch sidecar',
  patch_renderer: 'Patch renderer',
  block_release: 'Block release',
  document_warning: 'Document warning',
  escalate: 'Escalate',
};

export function getPdfImportMonitoringActionLabel(
  action: PdfImportMonitoringAction,
): string {
  return ACTION_LABELS[action] ?? String(action);
}
