-- Migration: Fix Report and Analysis Data RLS Policies
-- Purpose: Remove overly permissive policies and create secure user-based policies
-- Security: Users can only access reports/analyses for their clients or ones they created
-- Date: 2025-01-24

BEGIN;

-- ============================================
-- STEP 1: Drop existing permissive policies
-- ============================================

-- property_comparisons: Remove 4 overly permissive policies
DROP POLICY IF EXISTS "All authenticated users can create comparisons" ON property_comparisons;
DROP POLICY IF EXISTS "All authenticated users can delete all comparisons" ON property_comparisons;
DROP POLICY IF EXISTS "All authenticated users can update all comparisons" ON property_comparisons;
DROP POLICY IF EXISTS "All authenticated users can view all comparisons" ON property_comparisons;

-- Note: cash_flow_analyses, portfolio_reviews, portfolio_analysis_reports, borrowing_capacity_assessments
-- already had their public policies removed in Stage 1, but we need to add user-based policies

-- ============================================
-- STEP 2: Create secure policies for investment_reports
-- ============================================
-- Users can view reports they generated or reports for their clients (via client_property_id)

-- SELECT: Users can view reports they generated or reports for their clients
CREATE POLICY "Users can view reports they generated or for their clients"
  ON investment_reports FOR SELECT
  USING (
    -- Report was generated by the user
    (generated_by = auth.uid())
    OR
    -- Report is for a client property owned by the user
    EXISTS (
      SELECT 1 FROM client_properties cp
      JOIN clients c ON c.id = cp.client_id
      WHERE cp.id = investment_reports.client_property_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- INSERT: Users can create reports for their clients
CREATE POLICY "Users can create reports for their clients"
  ON investment_reports FOR INSERT
  WITH CHECK (
    -- Report is for a client property owned by the user
    EXISTS (
      SELECT 1 FROM client_properties cp
      JOIN clients c ON c.id = cp.client_id
      WHERE cp.id = investment_reports.client_property_id
      AND c.created_by::text = auth.uid()::text
    )
    AND
    -- Report generator must match authenticated user
    (generated_by = auth.uid() OR generated_by IS NULL)
  );

-- UPDATE: Users can update reports they generated or reports for their clients
CREATE POLICY "Users can update reports they generated or for their clients"
  ON investment_reports FOR UPDATE
  USING (
    -- Report was generated by the user
    (generated_by = auth.uid())
    OR
    -- Report is for a client property owned by the user
    EXISTS (
      SELECT 1 FROM client_properties cp
      JOIN clients c ON c.id = cp.client_id
      WHERE cp.id = investment_reports.client_property_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- DELETE: Users can delete reports they generated or reports for their clients
CREATE POLICY "Users can delete reports they generated or for their clients"
  ON investment_reports FOR DELETE
  USING (
    -- Report was generated by the user
    (generated_by = auth.uid())
    OR
    -- Report is for a client property owned by the user
    EXISTS (
      SELECT 1 FROM client_properties cp
      JOIN clients c ON c.id = cp.client_id
      WHERE cp.id = investment_reports.client_property_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- ============================================
-- STEP 3: Create secure policies for property_comparisons
-- ============================================
-- Users can only access comparisons they created

-- SELECT: Users can view their own comparisons
CREATE POLICY "Users can view their own comparisons"
  ON property_comparisons FOR SELECT
  USING (created_by = auth.uid());

-- INSERT: Users can create comparisons
CREATE POLICY "Users can create comparisons"
  ON property_comparisons FOR INSERT
  WITH CHECK (
    auth.role() = 'authenticated'
    AND (created_by = auth.uid() OR created_by IS NULL)
  );

-- UPDATE: Users can update their own comparisons
CREATE POLICY "Users can update their own comparisons"
  ON property_comparisons FOR UPDATE
  USING (created_by = auth.uid());

-- DELETE: Users can delete their own comparisons
CREATE POLICY "Users can delete their own comparisons"
  ON property_comparisons FOR DELETE
  USING (created_by = auth.uid());

-- ============================================
-- STEP 4: Create secure policies for cash_flow_analyses
-- ============================================
-- Users can only access analyses they created

-- SELECT: Users can view their own cash flow analyses
CREATE POLICY "Users can view their own cash flow analyses"
  ON cash_flow_analyses FOR SELECT
  USING (created_by = auth.uid());

-- INSERT: Users can create cash flow analyses
CREATE POLICY "Users can create cash flow analyses"
  ON cash_flow_analyses FOR INSERT
  WITH CHECK (
    auth.role() = 'authenticated'
    AND (created_by = auth.uid() OR created_by IS NULL)
  );

-- UPDATE: Users can update their own cash flow analyses
CREATE POLICY "Users can update their own cash flow analyses"
  ON cash_flow_analyses FOR UPDATE
  USING (created_by = auth.uid());

-- DELETE: Users can delete their own cash flow analyses
CREATE POLICY "Users can delete their own cash flow analyses"
  ON cash_flow_analyses FOR DELETE
  USING (created_by = auth.uid());

-- ============================================
-- STEP 5: Create secure policies for portfolio_reviews
-- ============================================
-- Users can access reviews for their clients

-- SELECT: Users can view reviews for their clients
CREATE POLICY "Users can view reviews for their clients"
  ON portfolio_reviews FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = portfolio_reviews.client_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- INSERT: Users can create reviews for their clients
CREATE POLICY "Users can create reviews for their clients"
  ON portfolio_reviews FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = portfolio_reviews.client_id
      AND c.created_by::text = auth.uid()::text
    )
    AND
    (reviewer_id = auth.uid() OR reviewer_id IS NULL)
  );

-- UPDATE: Users can update reviews for their clients
CREATE POLICY "Users can update reviews for their clients"
  ON portfolio_reviews FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = portfolio_reviews.client_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- DELETE: Users can delete reviews for their clients
CREATE POLICY "Users can delete reviews for their clients"
  ON portfolio_reviews FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = portfolio_reviews.client_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- ============================================
-- STEP 6: Create secure policies for portfolio_analysis_reports
-- ============================================
-- Users can access reports for their clients or reports they generated

-- SELECT: Users can view reports for their clients or reports they generated
CREATE POLICY "Users can view reports for their clients or they generated"
  ON portfolio_analysis_reports FOR SELECT
  USING (
    -- Report was generated by the user
    (generated_by = auth.uid())
    OR
    -- Report is for a client owned by the user
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = portfolio_analysis_reports.client_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- INSERT: Users can create reports for their clients
CREATE POLICY "Users can create reports for their clients"
  ON portfolio_analysis_reports FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = portfolio_analysis_reports.client_id
      AND c.created_by::text = auth.uid()::text
    )
    AND
    (generated_by = auth.uid() OR generated_by IS NULL)
  );

-- UPDATE: Users can update reports for their clients or reports they generated
CREATE POLICY "Users can update reports for their clients or they generated"
  ON portfolio_analysis_reports FOR UPDATE
  USING (
    -- Report was generated by the user
    (generated_by = auth.uid())
    OR
    -- Report is for a client owned by the user
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = portfolio_analysis_reports.client_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- DELETE: Users can delete reports for their clients or reports they generated
CREATE POLICY "Users can delete reports for their clients or they generated"
  ON portfolio_analysis_reports FOR DELETE
  USING (
    -- Report was generated by the user
    (generated_by = auth.uid())
    OR
    -- Report is for a client owned by the user
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = portfolio_analysis_reports.client_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- ============================================
-- STEP 7: Create secure policies for borrowing_capacity_assessments
-- ============================================
-- Users can access assessments for their clients

-- SELECT: Users can view assessments for their clients
CREATE POLICY "Users can view assessments for their clients"
  ON borrowing_capacity_assessments FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = borrowing_capacity_assessments.client_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- INSERT: Users can create assessments for their clients
CREATE POLICY "Users can create assessments for their clients"
  ON borrowing_capacity_assessments FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = borrowing_capacity_assessments.client_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- UPDATE: Users can update assessments for their clients
CREATE POLICY "Users can update assessments for their clients"
  ON borrowing_capacity_assessments FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = borrowing_capacity_assessments.client_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- DELETE: Users can delete assessments for their clients
CREATE POLICY "Users can delete assessments for their clients"
  ON borrowing_capacity_assessments FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = borrowing_capacity_assessments.client_id
      AND c.created_by::text = auth.uid()::text
    )
  );

-- ============================================
-- Security Model Explanation
-- ============================================
-- After this migration:
-- - investment_reports: Users can only access reports they generated or for their clients
-- - property_comparisons: Users can only access comparisons they created
-- - cash_flow_analyses: Users can only access analyses they created
-- - portfolio_reviews: Users can only access reviews for their clients
-- - portfolio_analysis_reports: Users can only access reports for their clients or they generated
-- - borrowing_capacity_assessments: Users can only access assessments for their clients
--
-- This ensures:
-- 1. Report and analysis data is protected from unauthorized access
-- 2. Users cannot access reports/analyses for other users' clients
-- 3. All access goes through authenticated edge functions
-- 4. Compliance with data protection regulations

COMMIT;

