-- Mark all clients from the spreadsheet as favorites
UPDATE clients
SET is_favorite = true, updated_at = now()
WHERE 
  -- Page 1 clients (35 clients)
  LOWER(CONCAT(primary_first_name, ' ', primary_surname)) IN (
    'rob hastings',
    'parth goyal',
    'chandra chandra sekhar',
    'satpal bahian',
    'gurinderjit singh',
    'jaspreet singh',
    'inderpreet singh',
    'nikhil reddy reddy',
    'denish lunagaria',
    'srikanth sureneni',
    'jahanara quoted',
    'jabbour simon',
    'alina kayastha',
    'prashant tiwari',
    'satchi solay',
    'viahal handa',
    'abdullah aslam',
    'dinesh chandra',
    'prateek arora',
    'max massimo max',
    'aleksandra jaworska jaworska',
    'swathi udumala',
    'salman ahmed',
    'sukhwinder singh',
    'ranjit singh',
    'hardik sanchala',
    'hassan riasat',
    'sunil rask',
    'arshdeep singh',
    'abdulla janjua',
    'shireen s kumar',
    'kamal deep',
    'anoop markose',
    'atul maggu'
  )
  OR LOWER(primary_email) IN (
    'rob.hasto@gmail.com',
    'parthgoyal@icloud.com',
    'sekhar.racharla@yahoo.com',
    'satpalsp@outlook.com',
    'gj.singh@indimex.com.au',
    'jassisaini202@yahoo.com',
    'is7753041@gmail.com',
    'nikhilreddy.koyadi@gmail.com',
    'denishl28@gmail.com',
    'sureneni.srikanth@gmail.com',
    'jqneela@gmail.com',
    'jim@prestigesparks.com.au',
    'alinakayastha33@gmail.com',
    'p2006.prashant@gmail.com',
    'spclassic88@gmail.com',
    'vishalpharma19@yahoo.com',
    'abdullahaslam058@gmail.com',
    'dineshchandra8@bigpond.com',
    'prateek.arora@y7mail.com',
    'mgiogrand@gmail.com',
    'alexjaworska@hotmail.com',
    'swathi.udumala1@gmail.com',
    'salmanahmed313@gmail.com',
    'sukhwindersingh163@gmail.com',
    'ranjitsingh117@yahoo.com',
    'hardiksanchala@gmail.com',
    'hassan0123ahmed@gmail.com',
    'sunilraskar@gmail.com',
    'arshmalhi1@gmail.com',
    'abdullllahhjaved@gmail.com',
    's.prasad40@hotmail.com',
    'kamd_81@yahoo.com',
    'anoopmarkose83@gmail.com',
    'magguatul@gmail.com',
    -- Page 2-4 clients
    'kassimseeni651@gmail.com',
    'kaimalie19@outlook.com',
    'sudhershanam@gmail.com',
    'architect_abhi5@yahoo.co.in',
    'sdl1991@outlook.com.au',
    'shalinibaran@gmail.com',
    'elonex98@yahoo.com'
  );